export { IdePage } from './IdePage';
export { MOPage } from './MOPage';
export { LandingPage } from './LandingPage';
export { SignIn } from './SignIn';
export { SignUp } from './SignUp';
export { HomePage } from './HomePage'
export { ResetPassword } from './ResetPassword'
export { PrivateRoute } from './PrivateRoute'
export { AdminSignIn } from './AdminSignIn'
export { TeacherQuizzes } from './TeacherQuizzes'
